# Generated by Django 5.0.9 on 2026-07-04 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0009_location_google_place_id_location_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="hours",
        ),
        migrations.RemoveField(
            model_name="location",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="location",
            name="website",
        ),
    ]
