# Generated by Django 5.0.9 on 2026-07-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0012_remove_location_gluten_free_verified_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Visit",
        ),
    ]
