# Generated by Django 5.0.9 on 2026-07-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0016_totpdevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemreview",
            name="private_notes",
            field=models.TextField(
                blank=True, help_text="Only visible to you — never shown to other users"
            ),
        ),
    ]
