# Generated by Django 5.0.9 on 2026-07-11 02:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0017_itemreview_private_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Public collections appear on your profile page.",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name="collection",
            unique_together={("created_by", "name")},
        ),
    ]
