# Generated by Django 5.0.9 on 2026-07-11 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0018_collection_is_public_alter_collection_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChainGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="location",
            name="chain_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Links this waypoint with other branches of the same chain (e.g. every Burger King), sharing their items/dishes and item reviews.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locations",
                to="tracker.chaingroup",
            ),
        ),
    ]
