# Generated by Django 5.0.9 on 2026-07-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0020_friendgroup_friendgroupjoinrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="featured_on",
            field=models.ManyToManyField(
                blank=True, related_name="featured_collections", to="tracker.location"
            ),
        ),
    ]
