# Generated by Django 5.0.9 on 2026-07-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0021_collection_featured_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="featured_on",
        ),
        migrations.AddField(
            model_name="collection",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
