# Generated by Django 5.0.9 on 2026-07-12 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0022_remove_collection_featured_on_collection_is_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="status",
        ),
    ]
