# Generated by Django 5.0.9 on 2026-07-12 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0023_remove_location_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="category",
        ),
    ]
